version: "2.1"
network_mode: host
volumes:
    # ca: "./ca:/ca"
    # plots_dir: "./plots:/plots"
    caDir:
services:
    chia:
        build:
            context: ./
            dockerfile: ./Dockerfile.template
            volumes:
                - 'caDir:/ca'
            labels: 
                io.balena.features.sysfs: '1'
        # networks:
        #     - overlay
        # extra_hosts: 
        #     - ""

