version: "2.1"
volumes:
    # ca: "./ca:/ca"
    # plots_dir: "./plots:/plots"
    ca: {}
services:
    chia:
        build:
            context: ./
            dockerfile: ./Dockerfile.template
        # networks:
        #     - overlay
        # extra_hosts: 
        #     - ""

